before_script:
  - python --version
  - ls /home/kode/android-ut-builds

stages:
  - test

test:
  stage: test
  only:
   - master
  tags:
   - qa-serv
  script:
   - pip install -r requirements.txt
   - pytest -v main.py

