before_script:
  - python --version
  - mkdir -p /qa-builds
  - ls /qa-builds

stages:
  - test

test:
  stage: test
  only:
   - yn
  tags:
   - qa-serv
  script:
   - pip install -r requirements.txt
   - behave @ut.featureset
