image: python:3.6

before_script:
  - python --version
  - export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/jre"
  - export ANDROID_HOME="/home/kode/android-sdk-linux"
  - export PATH=$JAVA_HOME/bin:$PATH
  - export PATH=$ANDROID_HOME/platform-tools:$PATH
  - export PATH=$ANDROID_HOME/tools:$PATH
  - export PATH=/usr/local/share/chromedriver:$PATH
  - echo $PATH
  - cd /usr/bin/
  - ls
stages:
  - test

test:
  stage: test
  only:
   - master
  tags:
   - qa-serv
  script:
   - pip install -r requirements.txt
   - pytest -v main.py

