image: butomo1989/docker-android-x86-7.1.1

before_script:
  - python3 --version
  - apt-get update
  - apt-get -y install python3-pip

stages:
  - test

test:
  stage: test
  only:
   - master
  tags:
   - qa-appium
  script:
   - python3 -m pip install -r requirements.txt
   - appium
   - python3 -m pytest -v main.py

